alias dc='docker-compose'
alias dcr='docker-compose run'
alias dcb='docker-compose build'
alias dcd='docker-compose down'
alias dce='docker-compose exec'
alias dcl='docker-compose logs'
alias dcf='docker-compose run --rm'
